/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ChatBox: typeof import('./components/ChatBox.vue')['default']
    ChatHistoryList: typeof import('./components/ChatHistoryList.vue')['default']
    ErrorBanner: typeof import('./components/ErrorBanner.vue')['default']
    EventLogViewer: typeof import('./components/EventLogViewer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./components/Sidebar.vue')['default']
    TaskQueuePanel: typeof import('./components/TaskQueuePanel.vue')['default']
    ThinkingProcess: typeof import('./components/ThinkingProcess.vue')['default']
    ToolMessage: typeof import('./components/ToolMessage.vue')['default']
    TraceLog: typeof import('./components/TraceLog.vue')['default']
    Welcome: typeof import('./components/Welcome.vue')['default']
    WorkflowGraphEditor: typeof import('./components/WorkflowGraphEditor.vue')['default']
    WorkflowRunNodes: typeof import('./components/WorkflowRunNodes.vue')['default']
  }
}
