/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ChatBox: typeof import('./components/ChatBox.vue')['default']
    ChatHistoryList: typeof import('./components/ChatHistoryList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./components/Sidebar.vue')['default']
    TraceLog: typeof import('./components/TraceLog.vue')['default']
    Welcome: typeof import('./components/Welcome.vue')['default']
  }
}
